#ifndef ERRORS_H
#define ERRORS_H

#define SUCCESS 0
#define POINT_READ_ER 1
#define WRONG_EDGE_INDEX 2
#define EMPTY_FIGURE 3
#define FIGURE_READ_ER 4
#define FIGURE_ALLOC_ER 5
#define OPEN_ER 6
#define EDGES_ALLOC_ER 7
#define DISPLAY_EDGES_ALLOC_ER 8
#define INCORRECT_FIGURE 9
#define UNINIT_FIGURE 10
#define WRONG_COMMAND 11
#define POINTS_ALLOC_ER 12
#define POINTS_READ_ER 13
#define EDGE_READ_ER 14
#define EDGES_READ_ER 15
#define INCORRECT_EDGES 16
#define DISP_POINTS_ALLOC_ER 17
#define INCORRECT_POINTS 18
#define INCORRECT_DISP_POINTS 19

#endif // ERRORS_H
